### PR TITLE
Maintenance/pdf modularization

### PR DESCRIPTION
**Pull request by petermao**
I'm trying to move all `pdf-tools`-specific functions out of `-core.el` and into `modules/-pdf.el`.  The first 3 commits are just renames so everything in the modules start with `org-noter-<module>--...`.   46e639afde004e709b656ed215a16172c9ebc686 moves the `-show-arrow` function, makes a hook and adds the moved function to the hook in the usual way.

In 7bd11455e482aeaef2b7a8faf5449ee182256b3a, I take the `(require 'pdf-tools)` out of `-core.el` and it breaks the packaged version of org-noter, but not my local copy.  Specifically, the arrow stops showing up and emacs claims it knows nothing about the pdf-tools function `pdf-view-current-overlay`.

In be255124f2b559744a7203a7c9348aa0a469e117, the explicit call outside of `condition-case` fixes the "bug," but that subverts the intent of the `condition-case` that was brought in at PR #13 to fix issue #9.

1aaea1297d34d7348e2be783b8d4e9ce86459d38 shows that the calls to `declare-function` have no effect on the behavior of the code.

### CODE REVIEW

**Comment by petermao** [comment]
If I go to the first "buggy" commit, 7bd11455e482aeaef2b7a8faf5449ee182256b3a, and byte-compile `modules/org-noter-pdf.el`, then the arrow doesnt work, with message:
`Error running timer ‘org-noter--show-arrow’: (invalid-function pdf-view-current-overlay)`
But `show-arrow` has no problems with the interpreted lisp file!

Compilation only produces warnings:
```
Compiling file /<path-to>/org-noter/modules/org-noter-pdf.el at Sun Apr 30 11:08:48 2023
Entering directory ‘/<path-to>/org-noter/modules/’
org-noter-pdf.el:35:1: Warning: variable ‘_’ not left unused

In org-noter-pdf--get-buffer-file-name:
org-noter-pdf.el:68:55: Warning: Unused lexical argument `mode'
org-noter-pdf.el:398:1: Warning: variable ‘_’ not left unused
```
no complaints against pdf-tools functions during compilation!

**Comment by petermao** [comment]
So my current understanding is that the `(require 'pdf-tools)` in the `condition-case` at https://github.com/org-noter/org-noter/blob/3856c1b60a2667378b82c65f2e10c9c22fc40fae/modules/org-noter-pdf.el#L29-L32 is not being executed in the byte-compiled code.  What to do?

**Comment by petermao** [comment]
@dmitrym0 @terlar @pepetr @uliw @rdiaz02 please pull and test [this branch](https://github.com/org-noter/org-noter/tree/maintenance/pdf-modularization), as you are known stake-holders in the changes being implemented.

**Comment by pepetr** [comment]
Works fine here, thanks a lot !

**Comment by dmitrym0** [comment]
@petermao I can't seem to reproduce this. Can you tell me what you need to do to get this error?

I manually invoke `org-noter--show-arrow` from your branch and it seems to work without errors.

My `org-noter-pdf.el` is byte compiled too:

image

**Comment by petermao** [comment]
> @petermao I can't seem to reproduce this. Can you tell me what you need to do to get this error?

which commit were you on?   if you're on the last one, it should work fine.  If you check out 7bd11455e482aeaef2b7a8faf5449ee182256b3a, then what I find is that the byte-compiled file won't show arrows.

**Comment by rdiaz02** [comment]
Works fine here too (I could only do limited testing, though).

**Comment by dmitrym0** [comment]
> which commit were you on? if you're on the last one, it should work fine. If you check out [7bd1145](https://github.com/org-noter/org-noter/commit/7bd11455e482aeaef2b7a8faf5449ee182256b3a), then what I find is that the byte-compiled file won't show arrows.

I tried 7bd11455e482aeaef2b7a8faf5449ee182256b3a. Both `org-noter-pdf--get-curent-view` and `org-noter--show-arrow` show up for me (at least in describe function).

**Comment by petermao** [comment]
With 7bd1145, when I run the compiled `modules/org-noter-pdf.elc`, no arrow shows up.  When I run the uncompiled `modules/org-noter-pdf.el`, it works fine.  The last commit should work in either case.

I think it's stable enough to merge.  We can revisit my ugly code if you (@dmitrym0) find a cleaner way to implement this: https://github.com/org-noter/org-noter/blob/d541042157c312d3ddf313b18ae35cad7c19b939/modules/org-noter-pdf.el#L29-L35

**Review by dmitrym0 — APPROVED** [review]

**Pull request merged**
