### PR TITLE
Bugfix/nov mode

### PR DESCRIPTION
**Pull request by petermao**
1. move NOV and DOC-VIEW depedent code from `org-noter-core` to `modules/org-noter-<doctype>.el`
2. fix bug in `modules/org-noter-nov`

### CODE REVIEW

**Comment by petermao** [comment]
@dmitrym0, let's fast-track this one.  I've tested the advice handling in nov and doc-view, the later made easier when I remembered that you made the clean-room emacs.

I think we have some nov-only users, and this will make org-noter functional for them again.

**Review by dmitrym0 — APPROVED** [review]
Thanks for doing this. 

Can we settle on a naming scheme?

`org-noter-<submodule>--<private_function>`?
`org-noter-<submodule>-<public_function>`? 

I think there's a lispy way to do this too?

**Comment by petermao** [comment]
> Can we settle on a naming scheme?
> 
> `org-noter-<submodule>--<private_function>`? `org-noter-<submodule>-<public_function>`?
> 
> I think there's a lispy way to do this too?

That's what I was aiming for.  I think I got everything in the modules.

**Comment by tlaso** [comment]
My setup is working again. I was having the «org-noter--doc-approx-location: Unknown document type nov-mode» error, but now it is gone. Thank your for your work, it made my day!

**Pull request merged**
