### PR TITLE
Feature/generalize file opening process

### PR DESCRIPTION
**Pull request by dmitrym0**
## Problem

I'd like to be able to modify the notes opening process. Right now it's assumed that only `Notes.org` file is to be used within a certain number of available directories.

I'd like to be able to override the process so that I can stores notes  files within my org-roam.

## Solution

Similar to other refactorings:

1. add a hook to be called when looking for a notes file
2. by default set the hook to call `org-noter--create-session-from-publication-file-default`. This is the original implementation of the notes file opening process.

## Checklist

- [x] I checked the code to make sure that it works on my machine.
- [x] I checked that the code works without my custom emacs config.
- [ ] I added unit tests. (covered by original unit tests)

## Steps to Test

This should be a completely transparent change:

1. Open a PDF file
2. `M-x org-noter`

Org-noter should launch.

### CODE REVIEW

**Comment by petermao** [comment]
Can you give an example of a hook function that you would use (maybe in `./docs/CUSTOMIZATIONS.org`)?

How does `defcustom org-noter-notes-search-path` fall short of your needs?

**Comment by dmitrym0** [comment]
> Can you give an example of a hook function that you would use (maybe in `./docs/CUSTOMIZATIONS.org`)?

Good idea. I'm essentially splitting/cleaning up #20. This PR creates the mechanism by which you can customize notes file selection process, and the next PR will actually implement org-roam integration.

> How does `defcustom org-noter-notes-search-path` fall short of your needs?

It funnels you into a pretty restive  workflow.  

There's a workflow demo here: https://github.com/org-noter/org-noter/issues/16#issuecomment-1501006661

or a live one on YouTube: https://youtu.be/54YFv-b6grQ?t=86

**Review by petermao — CHANGES_REQUESTED** [review]
Throughout the code, the two buffers are refered to as the "notes" buffer/file and the "document" buffer/file.  Let's not introduce the synonym "publication" for "document."  This will make the code easier for our future selves (or other maintainers) to grok.

Flycheck complains if you don't end the first line of the docstring with a period.

**Comment by dmitrym0** [comment]
> Throughout the code, the two buffers are refered to as the "notes" buffer/file and the "document" buffer/file. Let's not introduce the synonym "publication" for "document." This will make the code easier for our future selves (or other maintainers) to grok.
> 
> Flycheck complains if you don't end the first line of the docstring with a period.

Makes sense to me; will change "publication" to "document'.  If you wanted to rename something project wide, how would you do it? I've seen a few different approaches but I haven't actually used any of them. Need your emacs-fu 🤣

**Comment by dmitrym0** [comment]
I spent about 20 mins trying to get wgrep-mode to work, but it was inconsistent. I managed to change all occurrences of `publication` in the grep buffer, but when it saved, wgrep-replace only saved about half of them. Not sure why.

Anyway, replaced all occurrences of publication and fixed the doc string.

**Review by petermao — APPROVED** [review]
Take a look at the three commits I just made. I think this is OK to merge now, but please make sure I didn't introduce any problems.

Note that the unit tests we have in hand did not catch either of the bugs I found.

**Comment by dmitrym0** [comment]
Thanks for looking at this @petermao.

I over-relied on unit tests and didn't actually execute the code locally after I renamed it 🤦 

- added a simple test to run `org-noter`, though it doesn't actually verify anything, but if it doesn't blow up that's a good sign.
- added a test to ensure that `org-noter-create-session-from-document-hook` is not nil. As the default implementation of the file opening process is should *never* be nil.

**Comment by petermao** [comment]
Looks good -- I'll let you have the fun of pushing the big green button!

**Pull request merged**
